# -*- coding: utf-8 -*-
"""endtoendchatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AnYVlS2XJVvjdqFheSBoictYy7xMmtGV
"""

import os
import nltk
import ssl
import streamlit as st
import random
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

ssl._create_default_https_context = ssl._create_unverified_context
nltk.data.path.append(os.path.abspath("nltk_data"))
nltk.download('punkt')

intents = [
    {
        "tag": "greeting",
        "patterns": [
            "Hi", "Hello", "Hey", "Good morning", "Good evening", "What's up", "How's it going?",
            "Yo", "Hi there", "Hey there", "Greetings", "Hey buddy", "What's new?"
        ],
        "responses": [
            "Hello! How can I assist you with trading today?",
            "Hi there! Looking to make some smart investments?",
            "Hey! Let’s dive into the markets.",
            "Hi! Ready to talk stocks?",
            "Greetings! Need help with something specific in trading?"
        ]
    },
    {
        "tag": "goodbye",
        "patterns": [
            "Bye", "Goodbye", "See you", "Talk to you later", "Catch you later", "I'm done for now",
            "That's all", "Peace out", "Later", "See ya", "Ciao", "Thanks, bye"
        ],
        "responses": [
            "Goodbye! Happy trading!",
            "See you later. Keep an eye on those markets!",
            "Take care and invest wisely.",
            "Bye! Reach out anytime you need stock tips.",
            "Catch you later! Stay profitable."
        ]
    },
    {
        "tag": "thanks",
        "patterns": [
            "Thanks", "Thank you", "Thanks a lot", "Many thanks", "Much appreciated", "I appreciate it",
            "Thanks for the info", "Cool, thanks", "Thanks for your help", "That's helpful"
        ],
        "responses": [
            "You're welcome!", "Glad to help!", "Anytime! Good luck in the market!",
            "No problem!", "Happy to assist!"
        ]
    },
    {
        "tag": "stock_price",
        "patterns": [
            "What is the stock price of Apple", "Check Tesla stock", "Price of Google shares",
            "How much is Amazon trading at", "Current price of Microsoft", "Tell me the stock price of Infosys",
            "What’s the share price of TCS", "How’s Reliance doing today", "Price of HDFC shares",
            "Show me the stock price of Netflix", "Get stock quote for Meta"
        ],
        "responses": [
            "I can't provide real-time prices, but you can check Google Finance, Yahoo Finance, or your trading app.",
            "Real-time stock data is not available here. Try using your broker's platform or financial websites.",
            "Please use apps like Zerodha Kite, Groww, or TradingView for real-time prices."
        ]
    },
    {
        "tag": "market_hours",
        "patterns": [
            "What are stock market hours", "When does the market open", "When does trading start",
            "Is the market open now", "Trading hours in India", "When does NSE open",
            "What time does NYSE open", "Stock market closing time", "What’s the timing for BSE"
        ],
        "responses": [
            "In India, markets are open from 9:15 AM to 3:30 PM IST, Monday to Friday.",
            "The NYSE is typically open from 9:30 AM to 4:00 PM EST.",
            "Stock markets are usually closed on public holidays and weekends.",
            "Pre-market and after-hours trading may differ based on the exchange and broker."
        ]
    },
    {
        "tag": "buy_stock",
        "patterns": [
            "How do I buy stocks", "Where can I buy shares", "What app to use for trading",
            "Can I invest in stocks online", "Best way to buy stocks", "What platforms can I use to trade",
            "How to start buying stocks", "Is Zerodha good for beginners", "Can I invest through Upstox"
        ],
        "responses": [
            "You can buy stocks through platforms like Zerodha, Upstox, Groww, Robinhood, or ICICI Direct.",
            "Create a Demat and trading account with a broker, complete KYC, add funds, and you’re good to go.",
            "Online brokers make it easy to buy and sell stocks using apps and websites."
        ]
    },
    {
        "tag": "investing_vs_trading",
        "patterns": [
            "What's the difference between investing and trading", "Should I invest or trade",
            "Is trading better than investing", "Difference between trader and investor",
            "What’s long-term investing", "What’s intraday trading"
        ],
        "responses": [
            "Investing focuses on long-term growth, while trading aims for short-term profits.",
            "Traders buy and sell frequently to exploit market volatility; investors hold assets for years.",
            "Both have their pros and cons—it depends on your risk tolerance and financial goals."
        ]
    },
    {
        "tag": "stock_recommendation",
        "patterns": [
            "Which stock should I buy", "Best stocks to invest in", "What are the top stocks today",
            "Any stock recommendations", "Should I invest in TCS", "Is Reliance a good stock",
            "What are blue chip stocks", "Tell me good stocks to buy now"
        ],
        "responses": [
            "I can't provide specific financial advice, but look into large-cap, fundamentally strong companies.",
            "You may consider ETFs or index funds for diversification.",
            "Always research company financials and industry trends before investing."
        ]
    },
    {
        "tag": "risk_management",
        "patterns": [
            "How to manage risk in trading", "Tips for reducing losses", "What is stop-loss",
            "How to avoid big losses in stock market", "What are risk management strategies",
            "Should I use a stop-loss", "How to protect my capital in trading"
        ],
        "responses": [
            "Use stop-loss orders, diversify your portfolio, and follow a trading plan.",
            "Only risk a small portion of your capital per trade—1–2% is a common rule.",
            "Don't let emotions drive your trades; stick to your strategy."
        ]
    },
    {
        "tag": "portfolio",
        "patterns": [
            "What is a stock portfolio", "How to build a portfolio", "Diversify investments",
            "What should be in my portfolio", "How many stocks should I own",
            "Is diversification important", "Best way to build a beginner portfolio"
        ],
        "responses": [
            "A stock portfolio is your collection of investment holdings.",
            "Build a balanced portfolio with a mix of large-cap, mid-cap, and small-cap stocks.",
            "Diversification reduces risk—don’t put all your money into one stock or sector."
        ]
    },
    {
        "tag": "dividends",
        "patterns": [
            "What are dividends", "Do stocks give income", "How do dividends work",
            "Which companies pay dividends", "What is dividend yield", "Can I earn monthly income from stocks"
        ],
        "responses": [
            "Dividends are profit distributions to shareholders, often paid quarterly.",
            "Companies like Infosys, TCS, and HUL often pay regular dividends.",
            "You can earn passive income through dividend-paying stocks."
        ]
    },
    {
        "tag": "credit_score",
        "patterns": [
            "What is a credit score", "How do I check my credit score", "How can I improve my credit score",
            "Is credit score important for investing", "Credit score for opening trading account"
        ],
        "responses": [
            "A credit score reflects your creditworthiness, not your trading eligibility.",
            "You can check your credit score via platforms like CIBIL, Experian, or Credit Karma.",
            "Maintaining good repayment habits improves your score."
        ]
    }
]

# Create the vectorizer and classifier
vectorizer = TfidfVectorizer()
clf = LogisticRegression(random_state=0, max_iter=10000)

# Preprocess the data
tags = []
patterns = []
for intent in intents:
    for pattern in intent['patterns']:
        tags.append(intent['tag'])
        patterns.append(pattern)

# training the model
x = vectorizer.fit_transform(patterns)
y = tags
clf.fit(x, y)

def chatbot(input_text):
    input_text = vectorizer.transform([input_text])
    tag = clf.predict(input_text)[0]
    for intent in intents:
        if intent['tag'] == tag:
            response = random.choice(intent['responses'])
            return response

counter = 0

def main():
    global counter
    st.title("Chatbot")
    st.write("Welcome to the chatbot. Please type a message and press Enter to start the conversation.")

    counter += 1
    user_input = st.text_input("You:", key=f"user_input_{counter}")

    if user_input:
        response = chatbot(user_input)
        st.text_area("Chatbot:", value=response, height=100, max_chars=None, key=f"chatbot_response_{counter}")

        if response.lower() in ['goodbye', 'bye']:
            st.write("Thank you for chatting with me. Have a great day!")
            st.stop()

if __name__ == '__main__':
    main()